plopjs/plop

- .gitignore
- README.md
- example/plopfile.js
- example/templates/burger.txt
- example/templates/potatoes.txt
- mod/logic.js
Hi there!
*First of all: thanks a lot for this handy tool. It's easy to setup, configure and use. It's super-flexible compared to the custom Yeoman generator we used before — no need to publish a new version and ensure everyone is up-to-date. That's awesome ;-)*
In our main project we quickly ran into a use case: when we create a new module it can have a collection+model or just a model, it may need a single item view or a collection view or a composite view…
The current way to do it would be either:
- to create one generator per scenario, which would quickly scale into a monster 
- to create a module, then to create a collection, then to create a model…
That would be nice if **plop** asks us if we want a model or a collection+model right during module creation, and produces everything …
> Makes `actions` accept a function

- mod/logic.js
I want to include my plopfile as a dependency that I can include in different projects. For example, if I was in an angular application, I could generate a plopflie.js that looks something like this:
```js
module.exports = require('angular-plop');
```
To accomplish that, I want my templates to be relative to `__dirname`, the actual location of plopflie logic, and not the plopfile itself. I should be able to set the templates as absolute path. With the change I made, if you set your path as an absolute path it will just use that path. If you set your path as a relative path, then it will automatically join that path to the plopfile's path. 
I hope that makes sense.
> allow template paths to be absolute (or relative)

- plop.js
This fixes #2 and tries to confort to the specs listed at https://github.com/amwmedia/plop/pull/3#issuecomment-162761445
I think there needs to be some more discussion regarding the init output, it could start a generator just like any plop generator would (or `npm -i`) and I do think that's the way to go since 1) So many options there and 2) Dog food.
As a start, I thought it'd fit to have a `plop -i` generate the simplest of plopfiles => the one that's shown on the [readme file](https://github.com/amwmedia/plop#3-create-a-plopfilejs-at-the-root-of-your-project)
> Help screen and an init plopfile via cli --options

- README.md
Hi,
if a custom action doesn’t return anything, plop seems to get confused and exits without executing any actions further down the pipeline. You might want to change this behavior someday, but for now a docs update should be enough.
> More explicit docs for custom actions

- .gitignore
- src/plop.js
This should handle scenarios like #54.
Let's pretend a Handlebar helper is misspelled.
Before this PR:
After this PR:
It also put the error message in red to make the whole readable along the error type and path. The latter are only displayed if they exist.
I think it should cover broader failing scenario with better logs.
What do you think?
> Enhance error messages

- README.md
- src/console-out.js
- src/plop.js
I came across #37 and I found it was an easy one, so here it is:
I didn't put these info in the README. Instead I indicated how to display plop options with `plop --help`. That way information is not duplicated, which I feel less risky to get out of sync in the future.
Also, I dropped the `verbose` argument which didn't seem to do anything. I couldn't find it in the [liftoff doc](https://github.com/js-cli/js-liftoff#launchopts-callbackenv) neither.
Does that seems good to you?
> Document liftoff arguments

- README.md
- example/plopfile.js
- package.json
- src/console-out.js
- src/plop.js
Closes #39.
This requires https://github.com/amwmedia/node-plop/pull/39 first.
Calling `plop.setWelcomeMessage('[CUSTOM]'.yellow + ' What can I do for you?');` will display:
If you don't set a message, it will fallback on the default one − which is the current one.
> Customize the starting prompt

- src/console-out.js
Commit d07972ba0f6ce87545a87f84ba4224425b55254e in #87 added a default parameter which isn't supported in Node 4. As a result the `plop` library was no longer able to run in Node 4.
Making the lib Node 4 compatible again by replacing the default parameter with an ES5 equivalent. I verified this works, but installing in Node 4 and running `node src/plop.js`
Fixes #99
> Make Node 4 compatible

- src/plop.js
Modify the Success logging message, 
If the Line type is string 'function' then not adding it in the array otherwise splicing the type on the log array at position 2 for proper messaging output.
> if Line type is function, omitting the function as string

- src/console-out.js
- src/plop.js
This feature implements #109 by adding named bypass args by using `plop generator args -- --named args` style. Additionally, if args are bypassed in the wrong way (too many args or incorrectly named args), it will throw a help page listing all arguments. 
Things from #109 that were not added:
- Typings for generator options menu. I was unsure how you wanted to implement that, so I left it out for the initial commit
- Allowing `'_'` in named args passing values. This was done so that there wouldn't have to be breaking releases in `node-plop` for the initial feature set. If requested, I can create a seperate PR for that functionality
> Added feature: Named argument bypass

- README.md
- example/plopfile.js
This adds documentation for the new action functions `skip` and `transform` introduced in https://github.com/plopjs/node-plop/pull/155.
> Add documentation for skip and transform

- .gitignore
- README.md
- src/input-processing.js
- src/plop.js
The following PR comes from a need that I faced while trying to use `plop` in a project for my company:
We wanted to remove the need for `--` and migrate towards using one set of arguments for both the plop arg API (`--force`) and the generator arg API (`--argName`). This would allow the following command to run:
```
plop --argName "Hello" --force
```
Instead of the default:
```
plop  --force -- --argName "Hello"
```
This is not set by default in the `plop` command, but is provided as an alternative API for `Plop.launch` for those looking to extend `plop` into making their own CLI utility. 
Currently, the documentation does not mention a usecase like this, so as such I've created a new "further reading" documentation section that covers just this.
> Allow merging of plop args and generator args, improved docs

- README.md
- package.json
Since the repo has moved, update the urls! Luckily, github redirects, but it's still better to update.
> chore: update urls

- README.md
Some links to [custom-action-function](https://github.com/plopjs/plop#custom-action-function) section in [README](https://github.com/plopjs/plop/blob/master/README.md) have been corrected.
> docs: fix wrong markdown link

- src/plop.js
- tests/action-failure.spec.js
- tests/examples/action-failure/package.json
- tests/examples/action-failure/plopfile.js
Fixes #299
@crutchcorn, I tested your suggestion locally, and that did the trick. I took a stab at the test, which seems to test the right thing to me, but YYMV.
> Return error code on failures on actions

- package.json
I'm getting the following warning coming from this package:
```
node:63582) [DEP0151] DeprecationWarning: 
Package .../node_modules/plop/ has a "main" field set to "./src/plop", 
excluding the full filename and extension to the resolved file at "src/plop.js", imported from .../index.js.
Automatic extension resolution of the "main" field is deprecated for ES modules.
```
> Resolve extension of main field

- README.md
The code changes in this PR fix the issue of 404(No page found) for accessing the Synchronous Custom Action example. Now it is pointing to the right URL.
Issue: https://github.com/plopjs/plop/issues/306
> Fixed the issue of 404 doc link. Now the link points to correct example

- .changeset/old-balloons-look.md
- packages/node-plop/src/node-plop.js
- packages/node-plop/tests/load-assets-from-plopfile/load-assets-from-plopfile.spec.js
- packages/plop/plop-load.md
> This PR was originally made by @RobinKnipe in the `node-plop` dedicated repo and moved over by hand to me: https://github.com/plopjs/node-plop/pull/187
Currently the `load` function doesn't include all assets when the `includeCfg` option is set to `true`.
The suggested code change should allow a shorthand to include all assets:
```js
plop.load('plopfile', {}, true)
```
This is a fix for issue: plopjs/plop#326 
Suggested changes to the `plop.load` doc here: https://github.com/plopjs/plop/pull/243
> Shorthand to load all plop assets

- .github/workflows/test.yml
- .gitignore
- package.json
- turbo.json
- yarn.lock
In light of [recent news about Lerna's deprecation](https://twitter.com/tomasz_ducin/status/1519436453729734657), @amwmedia and I have discussed migrating to Turborepo to keep our dependencies up to date.
This PR implements Turborepo. Luckily, our migration is extremely trivial due to a lack of build step and minimal Lerna configuration prior
> chore: replace Lerna with Turborepo

- packages/plop/src/plop.d.ts
runActions and runPrompts are required by types definition, added PlopGeneratorConfig member to exports in plop. Fixes #339
> added PlopGeneratorConfig to exports in plop

- packages/node-plop/types/index.d.ts
Patching this temporarily while waiting for this PR is non-trivial. As such I'm forced to abandon the library or use skipLibCheck for my shared generator package and all of it's dependents. Would love to see this get merged quickly! Thank you!
> Use type alias for inquirer module to avoid typescript error. Closes #357

- packages/node-plop/src/actions/addMany.js
- packages/node-plop/tests/addMany-strip-extensions/addMany-strip-extensions.spec.js
- packages/node-plop/tests/addMany-strip-extensions/plopfile.js
Fixes #324
Nodes `path.parse` does not treat dot files as an extension. For example `path.parse('.gitignore')` results in the following:
`{ root: '', dir: '', base: '.gitignore', ext: '', name: '.gitignore' }`
Because `ext` is an empty string rather than '.gitignore', extensions were not being stripped properly from dot files due to the `path.parse(maybeFile.name).ext !== ""` clause.
> Ensure addMany actions strip extensions correctly on dot files

- packages/node-plop/src/prompt-bypass.js
- packages/node-plop/tests/prompt-bypass-checkbox/prompt-bypass-checkbox.spec.js
- packages/plop/tests/input-processing.spec.js
In order to address #345 I added a check for an empty value in the `checkbox` bypass.
```javascript
if (v === "") {
return [];
}
```
I think this solves the issue, but I haven't been able to test it from the top level. Is there another test file that I'm missing?
/cc @amwmedia @crutchcorn
> Empty checkbox bypass

- packages/node-plop/src/actions/append.js
- packages/node-plop/tests/dynamic-template-file/plopfile.js
resolves #351 by treating the templateFile property of the 'append' action the same way the 'modify' action does
> fix: Append action's templateFile string not processed by handlebars

- plop-load.md
Using `plop.load` within es6 modules requires the usage of `async/await`. This is well _documented_ within plops unit tests. It is sadly not documented anywhere else (yet) ;-)
This PR fixes that and adds the missing parts to the documentation. Reducing frustration of first-time-ploppers within modern JS projects.
> Update plop.load docs regarding async/await requirement in es6 modules

- packages/node-plop/package.json
- packages/plop/package.json
- packages/plop/tests/examples/action-failure/package.json
- packages/plop/tests/examples/add-action/package.json
- packages/plop/tests/examples/cjs-js/package.json
- packages/plop/tests/examples/cjs/package.json
- packages/plop/tests/examples/esm/package.json
- packages/plop/tests/examples/javascript/package.json
- packages/plop/tests/examples/mjs/package.json
- packages/plop/tests/examples/prompt-only/package.json
- packages/plop/tests/examples/wrap-plop/package.json
When updating to [plop 4](https://github.com/plopjs/plop/releases/tag/plop%404.0.0) and reading that support for Node 12, 14, and 16 was dropped, I was surprised that my Node 16 application was still able to install plop without a warning about the engine.
Updating these engines will ensure that consumers of plop will be notified on install that their version of node may be unsupported if it is below 18.
> fix(engines): update engines to match top level package

- packages/plop/package.json
- yarn.lock
Per https://github.com/crutchcorn/cli-testing-library/issues/3 @Waldeedle fixed some of the issues with Windows running on CI. This PR updates the dep version to bring that to Plop
> fix: windows ci usage

- README.md
Alright here's a first cut at the docs.
A couple suggestions to consider before merging:
1. Add an `--init-ts` switch for convenience. I added it [here](https://github.com/plopjs/plop/pull/427/files#diff-0e1d2f6ba310c5d8612a88994e5046a0b1f655606010658c0283db356fec6125R65) and can pull it in. Tests pass.
2. Test/verify that `plopfile.ts` is automatically searched. I believe Liftoff does, but it would be nice not to need `--plopfile=plopfile.ts`
3. There are [a couple test fixes](https://github.com/plopjs/plop/pull/427/files#diff-c9457e7b30292dd61fd2960ff81fa512203235db975a933794882645d7f61adc) I'd like to pull into this PR. The typescript test wasn't loading `plopfile.ts` and the `tsconfig.json` had a path error. All of this can be fixed and will work now with a simple `import 'tsx'` in …
> Typescript docs

- packages/plop/src/plop.d.ts
A small enhancement to export the `Actions` type used in `setGenerator`, which can be handy for Typescript development
> Enhancement: export Actions type

- README.md
- packages/plop/src/console-out.js
- packages/plop/src/input-processing.js
- packages/plop/tests/__snapshots__/input-processing.spec.js.snap
> feat: --init-ts

- packages/node-plop/package.json
- packages/node-plop/src/fs-promise-proxy.js
- yarn.lock
Uses `mkdir` from the built-in `fs` module instead (using `recursive: true`).
> perf: drop mkdirp

- packages/node-plop/build-scripts/clean.js
- packages/node-plop/package.json
- packages/node-plop/src/actions/_common-action-add-file.js
- packages/node-plop/tests/helpers/path.js
- packages/node-plop/tests/imported-custom-action/custom-action.js
- yarn.lock
Uses `rm` to remove directories instead of `del`.
> perf: use built-in fs.rm

- packages/node-plop/package.json
- packages/node-plop/src/node-plop.js
- yarn.lock
Switches from lodash for property path getting to `dlv`.
Note that dlv doesn't handle square-bracket indexing (e.g. `foo[0]`) so we simply replace `[` with `.` and strip `]`. This means `foo.bar[0]` becomes `foo.bar.0`, etc.
> perf: drop lodash
