plopjs/plop

example/plopfile.js, mod/logic.js, mod/plop-base.js, package.json
I also added a convenience method `addPrompt` so users cab  add 3rd party
prompts types to their generators.
See #9 for more info.
=> expose inquirer and handlebars so users can configure advanced options.

.gitignore, package.json, plop.js
=> Add liftoff support

README.md
just a small fix - love the idea of this project
=> edit: a letter

inquirer-prompts.md
I added new inquirer prompts for selecting index in an array where should be added a new element.
=> update custom inquirer prompts

src/plop.js
If 0 generator is found => emit an error and stop:
If only 1 generator is found => run it without asking (closes #67):
Otherwise, process as usual:
=> Handle when there is 0 or 1 generator in plopfile

README.md, package.json, src/plop.js
Attempting to resolve issue/feature request #32 
Added a `--force` flag and the ability to opt-in to overwriting on file generation in the `add` and `addMany` actions.
A corresponding PR has been submitted to the `node-plop` repo.
=> Add force flag and corresponding documentation

README.md
This documents the behavior that I mistook for a bug. More information here:
https://github.com/amwmedia/node-plop/issues/69
=> add documentation for addMany's globOptions input property

example/plopfile.js
Modified example/index.js file, to fix grammatical mistakes in the comments.
=> Fixed spelling mistakes in example

src/plop.js
Consume the action as they are executed, rather than waiting for them all to be finished.
Dependant on https://github.com/amwmedia/node-plop/pull/91
=> Log success/failure after each action

src/bypass.js
Fixes #151 
Not much else to say about this one.
=> Add missing import of chalk

README.md
Just in case. You never know who might get tripped up by missing steps in the documentation.
Great project by the way!
=> Documentation(README.md): add example NPM script

src/console-out.js, src/plop.js
=> Adds --dest flag that sets the destBasePath

src/bypass.js
Fix #165. Detect when generator prompts is a function and ignore the bypass
=> Fix Issue #165

bin/plop.js, package.json, src/plop.js
- Export Plop and run function from the `./src/plop.js`
- Separate the bin folder to `./bin/plop.js`
=> build: exporting assets and separating bin file

README.md, index.d.ts, package.json, src/plop.d.ts
Replaces #147, per https://github.com/amwmedia/plop/pull/147#issuecomment-509387167
Subject to change; blocked by amwmedia/node-plop#111.
=> Add TypeScript declarations

src/console-out.js
This PR adds support for a new action result type of `"skip"`, for a better CLI experience with the new `skip` function.
This PR pairs with https://github.com/plopjs/node-plop/pull/159
=> Add support for skip action result

README.md, src/plop.js
Fixes #228 
I have tested locally and it works.
I've added some notes to the README, feel free to improve them/suggest improvements.
Let me know your thoughts.
=> Config dest path globally for wrapper

package-lock.json
```
found 47 vulnerabilities (39 low, 2 moderate, 6 high)
```
=> NPM security fixes

README.zh.md
Add README.zh.md. Related with #257.
=> chore: Add README.zh.md Related with #257

packages/node-plop/src/generator-runner.js
a patch for issue: https://github.com/plopjs/plop/issues/404
=> fix(node-plop): type assertion is not working for vm array

packages/plop/package.json, packages/plop/src/plop.js, yarn.lock
Switches to nanospinner which is much smaller.
=> perf: use nanospinner for spinners
